Remove a transiant dependency
This is used by flake so let flake manage the version is wants

```
 ERROR: Cannot install -r requirements/requirements_development.txt (line 6) and pycodestyle==2.6.0 because these package versions have conflicting dependencies.

The conflict is caused by:
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
    The user requested pycodestyle==2.6.0
    flake8 3.9.1 depends on pycodestyle<2.8.0 and >=2.7.0
```